Cadastro de país
RaimundoUdia/nosso-site-de-viagens pull request #1
Opened 2020-04-27 14:06 UTC by RaimundoUdia

2020-04-27 15:00 UTC, albertotavareszup requested changes

2020-04-27 15:00 UTC, albertotavareszup commented on nosso-site-de-viagens/Controllers/PaisController.cs
> +        public async Task<ActionResult<Pais>> Post(Pais model)
*Separamos as bordas externas do sistema do seu núcleo. Não ligamos parâmetros de requisição externa com objetos de domínio diretamente, assim como não serializamos objetos de domínio para respostas de API.*

Oi Raimundo, receber o objeto que faz parte do domínio direto na rota, que é a borda mais externa da aplicação deixa o contrato muito frágil. Qualquer remoção de método na classe  pode afetar o contrato, assim como qualquer adição de método de acesso pode também. Em geral minha recomendação, mesmo para casos simples como esse, é sempre criar classes específicas para receber os dados da requisições. No caso do c#, seria o lance da ViewModel mesmo.

2020-04-27 15:00 UTC, albertotavareszup commented on nosso-site-de-viagens/Controllers/PaisController.cs
> +        public async Task<ActionResult<Pais>> Post(Pais model)
Outro detalhe, aí por conta da minha ignorância no processo de validação aqui. Se o nome vier em branco, o que vai ser retornado para o cliente? Um json estruturado com o problema de validação?

2020-04-27 15:00 UTC, albertotavareszup commented on nosso-site-de-viagens/Controllers/PaisController.cs
> +            _context.Pais.Add(model);
*A complicação do nosso é código é proporcional a complicação da nossa feature. Quanto mais simples, melhor.*

Essa linha eu adoro. Sem repositório, service ou qualquer coisa. Acessando o contexto objeto relacional direto e mandando ver no banco.

2020-04-27 15:00 UTC, albertotavareszup commented on nosso-site-de-viagens/Controllers/PaisController.cs
> +        public async Task<ActionResult<Pais>> Post(Pais model)
Só para deixar claro, eu entendo que a adição de uma nova classe complica um pouco mais o sistema, eu sempre analiso isso de forma lógica, que nem eu descrevo aqui:  

*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho. Uma leitura simples e que introduz bem o assunto https://www.sonarsource.com/resources/white-papers/cognitive-complexity.html*

Mas um dos critérios para criar novas classes é quando elas resolvem algo que as construções da linguagem sozinhas não permitem. E esse é um caso que eu entendo essa necessidade.

2020-04-27 15:00 UTC, albertotavareszup commented on nosso-site-de-viagens/Models/Pais.cs
> +        public int Id { get; set; }
*Idealmente, todo código escrito deveria ser chamado por alguém. Se não tem ninguém chamando, ele não deveria existir.*

Pelo que eu entendi o id é auto gerado e o nome é obrigatório. Então não precisamos de setters para o id, nesse momento nem getters. A mesma coisa vale para o nome. Como fazer para um objeto do tipo Pais só ser construído com um nome?

2020-04-27 15:00 UTC, asouza-zup commented on nosso-site-de-viagens/Models/Pais.cs
> +        [Required(ErrorMessage = "O nome é obrigatório")]
*Protegemos as bordas do sistema como se não houvesse amanhã.*

Acho que está tudo bem deixar essa annotation/decorator/attribute aqui também. Mas o fluxo do sistema não deveria chegar nesse ponto com um nome em estado inválido. Aqui você só deixar a annotation e na classe que representa o formulário deixar a annotation com a mensagem em português.

2020-04-27 15:08 UTC, RaimundoUdia commented on nosso-site-de-viagens/Controllers/PaisController.cs
> +            _context.Pais.Add(model);
Certo entao o ideal seria eu criar um Repositório antes de enviar para o banco?

2020-04-27 17:05 UTC, asouza-zup commented on nosso-site-de-viagens/Controllers/PaisController.cs
> +            _context.Pais.Add(model);
Opa, não não. Ficou ótimo sim! Não precisa adicionar abstração que não é necessária :). Essa parte aqui está ótima!

2020-04-27 18:17 UTC, RaimundoUdia commented on nosso-site-de-viagens/Models/Pais.cs
> +        public int Id { get; set; }
public class Pais
    {
        [Key]
        public int Id;

        [Required]
        public string Nome;
    }

2020-04-27 18:19 UTC, RaimundoUdia commented on nosso-site-de-viagens/Models/Pais.cs
> +        [Required(ErrorMessage = "O nome é obrigatório")]
vc fala para colocar na ViewModel a mensagem de erro?

2020-04-27 18:22 UTC, RaimundoUdia commented on nosso-site-de-viagens/Controllers/PaisController.cs
> +        public async Task<ActionResult<Pais>> Post(Pais model)
se o nome vier em branco vai aparecer assim para o cliente.
![image](https://user-images.githubusercontent.com/59450902/80406692-da7a2300-889a-11ea-8bbd-79ce18f6bb34.png)

2020-04-27 18:45 UTC, asouza-zup commented on nosso-site-de-viagens/Models/Pais.cs
> +        public int Id { get; set; }
Agora só falta o construtor, é isso?

2020-04-27 18:46 UTC, asouza-zup commented on nosso-site-de-viagens/Models/Pais.cs
> +        [Required(ErrorMessage = "O nome é obrigatório")]
A mensagem fica no atributo da ViewModel, isso :).

2020-04-27 19:41 UTC, RaimundoUdia commented on nosso-site-de-viagens/Models/Pais.cs
> +        public int Id { get; set; }
Dei uma estudada aqui e nas propriedade da model deve possuir os métodos get e set, definidos de forma padrão/vazia. Isso é necessário para que o Entity Framework possa preencher essa propriedade dinamicamente.

2020-04-28 18:33 UTC, RaimundoUdia commented on nosso-site-de-viagens/Models/Pais.cs
> +        public int Id { get; set; }
seria como esta abaixo para evitar de nascer um pais sem nome.

public class Pais
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Nome { get; private set; }

        public Pais(string nome)
        {
            Nome = nome;
        }
    }

2020-04-28 22:50 UTC, albertotavareszup requested changes
Opa, só um comentário a mais :). Mas é isso aí!

2020-04-28 22:50 UTC, asouza-zup commented on nosso-site-de-viagens/Controllers/PaisController.cs
> +        public async Task<IActionResult> Create(PaisViewModel paisViewModel)
A validação é aplicada de maneira automática?

2020-04-28 22:50 UTC, asouza-zup commented on nosso-site-de-viagens/Models/Pais.cs
> +        public int Id { get; set; }
pode ser tudo privado? Qual o erro que dá se você deixa tudo privado?  Por conta desse pilar aqui :). 

*A sua api deve deixar claro o caminho que deve ser seguido pelo ponto do código que decide usá-la. Não espere que ninguém lembre de invocar nada. Faça de tudo para gerar obrigações. Quanto mais específico é seu código, menos democrático ele é.* 

Vamos tentar restringir o máximo que der.

2020-04-28 22:50 UTC, asouza-zup commented on nosso-site-de-viagens/Models/Pais.cs
> +        public Pais(string nome)
Nice! É isso aí! Agora nenhum pais é construído sem nome.

2020-04-29 12:43 UTC, RaimundoUdia commented on nosso-site-de-viagens/Controllers/PaisController.cs
> +        public async Task<IActionResult> Create(PaisViewModel paisViewModel)
sim quando usamos o Required ele faz a validação do campo automatica não deixando fazer o post se nao preencher o campo retornando o status 400 bad request e dando a mensagem que foi colocada na PaisViewModel.

2020-04-29 13:15 UTC, RaimundoUdia commented on nosso-site-de-viagens/Models/Pais.cs
> +        public Pais(string nome)
Sobre deixar privato o Id não pode porque precisa ser publico para que o entity consiga acessar as propiedades do campo e fazer o mapeamento do mesmo.

2020-04-29 19:12 UTC, asouza-zup commented on nosso-site-de-viagens/Controllers/PaisController.cs
> +        public async Task<IActionResult> Create(PaisViewModel paisViewModel)
Massa! É até bom que já me ajuda a revisar os outros códigos também :P. Não precisa checar ModelState nem nada.

2020-04-29 19:13 UTC, asouza-zup commented on nosso-site-de-viagens/Models/Pais.cs
> +        public Pais(string nome)
Fechado. Só para garantir, tanto o get quanto o set aí do nome ta privado né?

2020-04-29 19:19 UTC, RaimundoUdia commented on nosso-site-de-viagens/Models/Pais.cs
> +        public Pais(string nome)
Somente o set o get se eu colocar ele privado da o seguinte erro abaixo.
![image](https://user-images.githubusercontent.com/59450902/80637348-3bd5f980-8a35-11ea-8af9-ba5f4c0739fa.png)

2020-04-30 13:26 UTC, RaimundoUdia commented on nosso-site-de-viagens/Models/Pais.cs
> +        public int Id { get; set; }
Posso fazer da seguinte forma colocar private no set, como abaixo:
 public class Pais
    {
        [Key]
        public int Id { get; private set; }

        [Required]
        public string Nome { get; private set; }

        public Pais(string nome)
        {
            Nome = nome;
        }
    }

2020-04-30 17:59 UTC, albertotavareszup approved these changes

2020-04-30 18:28 UTC, merged